import { Injectable, NotFoundException, ConflictException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository, DataSource, ILike } from 'typeorm';
import { Material } from './material.entity';
import { CreateMaterialDto } from './dto/create-material.dto';
import { UpdateMaterialDto } from './dto/update-material.dto';
import { QuickCreateMaterialDto } from './dto/quick-create-material.dto';

@Injectable()
export class MaterialesService {
  constructor(
    @InjectRepository(Material)
    private readonly materialRepository: Repository<Material>,
    private readonly dataSource: DataSource,
  ) {}

  async create(createMaterialDto: CreateMaterialDto): Promise<Material> {
    // 1. Check uniqueness CI for nombre
    await this.validarUnicidadNombre(createMaterialDto.nombre);

    return await this.dataSource.transaction(async (manager) => {
      // 2. Handle code: manual or autogenerated
      let codigo = createMaterialDto.codigo;
      if (!codigo) {
        const result = await manager.query('SELECT generar_codigo_material() AS codigo');
        codigo = result[0].codigo;
      }

      const { categoriaId, unidadId, proveedorPrincipalId, ...rest } = createMaterialDto;
      
      const material = manager.create(Material, {
        ...rest,
        codigo,
      });

      if (categoriaId) material.categoria = { id: categoriaId } as any;
      if (unidadId) material.unidad = { id: unidadId } as any;
      if (proveedorPrincipalId) material.proveedorPrincipal = { id: proveedorPrincipalId } as any;

      return await manager.save(Material, material);
    });
  }

  async quickCreate(dto: QuickCreateMaterialDto): Promise<Material> {
    await this.validarUnicidadNombre(dto.nombre);

    return await this.dataSource.transaction(async (manager) => {
      const result = await manager.query('SELECT generar_codigo_material() AS codigo');
      const codigo = result[0].codigo;

      const material = manager.create(Material, {
        nombre: dto.nombre,
        descripcion: dto.descripcion,
        codigo,
        categoria: dto.categoriaId ? ({ id: dto.categoriaId } as any) : null,
        unidad: { id: dto.unidadId } as any,
      });

      return await manager.save(Material, material);
    });
  }

  async buscar(query: string): Promise<Material[]> {
    if (!query) return this.findAll();

    // Hybrid search: Trigram on name, ILike on code, array overlap on keywords
    return await this.materialRepository.createQueryBuilder('m')
      .leftJoinAndSelect('m.categoria', 'c')
      .leftJoinAndSelect('m.unidad', 'u')
      .leftJoinAndSelect('m.proveedorPrincipal', 'p')
      .where('m.nombre % :q', { q: query })
      .orWhere('m.codigo ILIKE :qPrefix', { qPrefix: `${query}%` })
      .orWhere('m.codigo_proveedor ILIKE :qPrefix', { qPrefix: `${query}%` })
      .orWhere(':q = ANY(m.keywords)', { q: query })
      .orderBy('similarity(m.nombre, :q)', 'DESC')
      .getMany();
  }

  async findAll(): Promise<Material[]> {
    return this.materialRepository.find({ 
      relations: ['categoria', 'unidad', 'proveedorPrincipal'],
      order: { codigo: 'ASC' } 
    });
  }

  async findOne(id: number): Promise<Material> {
    const material = await this.materialRepository.findOne({ 
      where: { id },
      relations: ['categoria', 'unidad', 'proveedorPrincipal']
    });
    if (!material) {
      throw new NotFoundException(`Material #${id} no encontrado`);
    }
    return material;
  }

  async update(id: number, updateMaterialDto: UpdateMaterialDto): Promise<Material> {
    const material = await this.findOne(id);
    
    if (updateMaterialDto.nombre && updateMaterialDto.nombre.toLowerCase() !== material.nombre.toLowerCase()) {
      await this.validarUnicidadNombre(updateMaterialDto.nombre, id);
    }

    const { categoriaId, unidadId, proveedorPrincipalId, ...rest } = updateMaterialDto;
    Object.assign(material, rest);

    if (categoriaId !== undefined) {
      material.categoria = categoriaId ? ({ id: categoriaId } as any) : null;
    }
    if (unidadId !== undefined) {
      material.unidad = unidadId ? ({ id: unidadId } as any) : null;
    }
    if (proveedorPrincipalId !== undefined) {
      material.proveedorPrincipal = proveedorPrincipalId ? ({ id: proveedorPrincipalId } as any) : null;
    }

    return this.materialRepository.save(material);
  }

  async remove(id: number): Promise<void> {
    const material = await this.findOne(id);
    material.activo = !material.activo;
    await this.materialRepository.save(material);
  }

  private async validarUnicidadNombre(nombre: string, excludeId?: number) {
    const query = this.materialRepository.createQueryBuilder('m')
      .where('LOWER(m.nombre) = LOWER(:nombre)', { nombre });
    
    if (excludeId) {
      query.andWhere('m.id != :id', { id: excludeId });
    }

    const existing = await query.getOne();
    if (existing) {
      throw new ConflictException(`Ya existe un material con el nombre "${nombre}" (unicidad case-insensitive)`);
    }
  }
}
